// This file is auto-generated by Supabase
// Type definitions for your database schema
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      players: {
        Row: {
          id: string
          user_id: string | null
          name: string
          image_url: string | null
          primary_position: string
          player_number: number | null
          rarity: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id?: string
          name: string
          image_url?: string | null
          primary_position: string
          player_number?: number | null
          rarity?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          image_url?: string | null
          primary_position?: string
          player_number?: number | null
          rarity?: string
          created_at?: string
          updated_at?: string
        }
      }
      player_stats: {
        Row: {
          player_id: string
          pace: number
          shooting: number
          passing: number
          dribbling: number
          defending: number
          physical: number
          vote_count: number
          updated_at: string
        }
        Insert: {
          player_id: string
          pace?: number
          shooting?: number
          passing?: number
          dribbling?: number
          defending?: number
          physical?: number
          vote_count?: number
          updated_at?: string
        }
        Update: {
          player_id?: string
          pace?: number
          shooting?: number
          passing?: number
          dribbling?: number
          defending?: number
          physical?: number
          vote_count?: number
          updated_at?: string
        }
      }
      stat_votes: {
        Row: {
          id: string
          voter_id: string
          player_id: string
          pace: number
          shooting: number
          passing: number
          dribbling: number
          defending: number
          physical: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          voter_id: string
          player_id: string
          pace: number
          shooting: number
          passing: number
          dribbling: number
          defending: number
          physical: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          voter_id?: string
          player_id?: string
          pace?: number
          shooting?: number
          passing?: number
          dribbling?: number
          defending?: number
          physical?: number
          created_at?: string
          updated_at?: string
        }
      }
      teams: {
        Row: {
          id: string
          name: string
          color: string
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          color?: string
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          color?: string
          created_at?: string
        }
      }
      team_members: {
        Row: {
          id: string
          team_id: string
          player_id: string
          created_at: string
        }
        Insert: {
          id?: string
          team_id: string
          player_id: string
          created_at?: string
        }
        Update: {
          id?: string
          team_id?: string
          player_id?: string
          created_at?: string
        }
      }
      polls: {
        Row: {
          id: string
          title: string
          description: string | null
          poll_type: string
          active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          title: string
          description?: string | null
          poll_type?: string
          active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          title?: string
          description?: string | null
          poll_type?: string
          active?: boolean
          created_at?: string
        }
      }
      poll_options: {
        Row: {
          id: string
          poll_id: string
          option_text: string
          votes: number
          created_at: string
        }
        Insert: {
          id?: string
          poll_id: string
          option_text: string
          votes?: number
          created_at?: string
        }
        Update: {
          id?: string
          poll_id?: string
          option_text?: string
          votes?: number
          created_at?: string
        }
      }
      poll_votes: {
        Row: {
          id: string
          poll_id: string
          option_id: string
          voter_id: string
          created_at: string
        }
        Insert: {
          id?: string
          poll_id: string
          option_id: string
          voter_id: string
          created_at?: string
        }
        Update: {
          id?: string
          poll_id?: string
          option_id?: string
          voter_id?: string
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
